AOTS/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
# from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView, TemplateView
from rest_framework import routers

from stars import views as star_views
from stars.api.views import ProjectViewSet

router = routers.DefaultRouter()
router.register(r'projects', ProjectViewSet)

urlpatterns = [
                  path('', RedirectView.as_view(pattern_name='projects')),
                  path(
                      "robots.txt",
                      TemplateView.as_view(
                          template_name="robots.txt",
                          content_type="text/plain",
                      ),
                  ),

                  path(
                      'w/documentation/',
                      TemplateView.as_view(
                          template_name='documentation.html'
                      )
                  ),
                  path(
                      'w/projects/',
                      star_views.project_list,
                      name='projects',
                  ),
                  path(
                      'w/<slug:project>/',
                      RedirectView.as_view(pattern_name='dash:dashboard')
                  ),
                  path(
                      'w/<slug:project>/systems/',
                      include('stars.urls', namespace='systems')
                  ),
                  path(
                      'w/<slug:project>/observations/',
                      include(
                          'observations.urls',
                          namespace='observations'
                      )
                  ),
                  path(
                      'w/<slug:project>/dash/',
                      include('dash.urls', namespace='dash')
                  ),
                  path(
                      'w/<slug:project>/observations/',
                      RedirectView.as_view(
                          pattern_name='observations:observatory_list'
                      )
                  ),
                  path(
                      'w/<slug:project>/analysis/',
                      include('analysis.urls', namespace='analysis')
                  ),
                  path(
                      'w/<slug:project>/dashboard/',
                      RedirectView.as_view(pattern_name='dash:dashboard')
                  ),

                  path('api/', include(router.urls), name='project-api'),
                  path(
                      'api/systems/',
                      include("stars.api.urls", namespace='systems-api')
                  ),
                  path(
                      'api/observations/',
                      include(
                          "observations.api.urls",
                          namespace='observations-api'
                      )
                  ),
                  path(
                      'api/analysis/',
                      include(
                          "analysis.api.urls",
                          namespace='analysis-api'
                      )
                  ),
                  path(
                      'users/',
                      include(
                          "users.urls",
                          namespace='users'
                      )
                  ),

                  path(r'admin/', admin.site.urls),

                  # path('', RedirectView.as_view(url='/stars/stars/', permanent=False)),
                  # path('stars/', include('stars.urls', namespace='stars'), name='stars'),
                  # path('observations/', include('observations.urls'), name='observations'),
                  # path('analysis/', include('analysis.urls'), name='analysis'),

                  # path(r'api/stars/', include("stars.api.urls"), name='stars-api'),
                  # path(r'api/observations/', include("observations.api.urls"), name='observations-api'),
                  # path(r'api/analysis/', include("analysis.api.urls"), name='analysis-api'),

                  # path(r'^login/$', auth_views.login, name='login'),
                  # path(r'^logout/$', auth_views.logout, {'next_page': '/stars/stars'}, name='logout'),
                  # path(r'^change-password/$', auth_views.password_change, name='change-pwd'),
                  # path(r'^password-change-done/$', auth_views.password_change_done, name='password_change_done'),

                  # include all relevant user login/logout stuff. This includes:
                  #  accounts/login/ [name='login']
                  #  accounts/logout/ [name='logout']
                  #  accounts/password_change/ [name='password_change']
                  #  accounts/password_change/done/ [name='password_change_done']
                  #  accounts/password_reset/ [name='password_reset']
                  #  accounts/password_reset/done/ [name='password_reset_done']
                  #  accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
                  #  accounts/reset/done/ [name='password_reset_complete']
                  path('accounts/', include('django.contrib.auth.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

observations/api/urls.py
from django.urls import include, path
from rest_framework import routers

from .views import (
    SpectrumViewSet,
    UserInfoViewSet,
    SpecFileViewSet,
    RawSpecFileViewSet,
    processSpectrum,
    processSpecfile,
    processRawSpecfile,
    getSpecfileHeader,
    LightCurveViewSet,
    processLightCurve,
    getLightCurveHeader,
    ObservatoryViewSet,
    getSpecfilePath,
    getRawSpecfilePath,
    getSpecfileRawPath,
    getLightCurvePath,
    bulkUploadSpectra, bulkDownloadSpectra
)

app_name = 'observations-api'

router = routers.DefaultRouter()
router.register(r'spectra', SpectrumViewSet)
router.register(r'userinfo', UserInfoViewSet)
router.register(r'specfiles', SpecFileViewSet)
router.register(r'rawspecfiles', RawSpecFileViewSet)
router.register(r'lightcurves', LightCurveViewSet)
router.register(r'observatories', ObservatoryViewSet)

urlpatterns = [
    path('', include(router.urls)),
    #    Spectra
    path(
        'spectra/<int:spectrum_pk>/process/',
        processSpectrum,
        name='process_spectrum',
    ),
    #    SpecFiles
    path(
        'specfiles/<int:specfile_pk>/process/',
        processSpecfile,
        name='process_specfile',
    ),
    path(
        'specfiles/<int:specfile_pk>/header/',
        getSpecfileHeader,
        name='specfile_header',
    ),
    path(
        'specfiles/<int:specfile_pk>/path/',
        getSpecfilePath,
        name='specfile_path',
    ),
    path(
        'specfiles/<int:specfile_pk>/raw_path/',
        getSpecfileRawPath,
        name='specfile_rawpath',
    ),
    #    RawSpecFiles
    path(
        'rawspecfiles/<int:rawspecfile_pk>/process/',
        processRawSpecfile,
        name='process_rawspecfile',
    ),
    path(
        'rawspecfiles/<int:rawspecfile_pk>/path/',
        getRawSpecfilePath,
        name='rawspecfile_path',
    ),
    #    Lightcurves
    path(
        'lightcurves/<int:lightcurve_pk>/process/',
        processLightCurve,
        name='process_lightcurve',
    ),
    path(
        'lightcurves/<int:lightcurve_pk>/header/',
        getLightCurveHeader,
        name='lightcurve_header',
    ),
    path(
        'lightcurves/<int:lightcurve_pk>/path/',
        getLightCurvePath,
        name='lightcurve_path',
    ),
    path(
        'api-spec-upload/',
        bulkUploadSpectra,
        name='api-spec-upload',
    ),
    path(
        'api-spec-download/',
        bulkDownloadSpectra,
        name='api-spec-download',
    ),
]

observations/urls.py
from django.urls import path

from . import views

app_name = 'observations'
urlpatterns = [
    #   Spectra
    path('spectra/', views.spectra_list, name='spectra_list'),
    path(
        'spectra/<int:spectrum_id>/',
        views.spectrum_detail,
        name='spectrum_detail',
    ),
    path('spectra/upload', views.add_spectra, name='spectra_upload'),
    #   SpecFiles
    path('specfiles/', views.specfile_list, name='specfile_list'),
    #   RawSpecFiles
    path('rawspecfiles/', views.rawspecfile_list, name='rawspecfile_list'),
    #   Lightcurves
    path('lightcurves/', views.lightcurve_list, name='lightcurve_list'),
    path(
        'lightcurves/<int:lightcurve_id>/',
        views.lightcurve_detail,
        name='lightcurve_detail',
    ),
    #   Observatories
    path('observatories/', views.observatory_list, name='observatory_list'),
]

stars/urls.py
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path
from django.views.generic.base import RedirectView

from . import views

app_name = 'systems'
urlpatterns = [
    path('stars/', views.star_list, name='star_list'),
    path('stars/<int:star_id>', views.star_detail, name='star_detail'),
    path('stars/<int:star_id>/edit', views.star_edit, name='star_edit'),
    path('tags/', views.tag_list, name='tag_list'),
    path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")),
    ),
]

observations/forms.py
# import re
# import datetime

from django import forms

from stars.forms import RAField, DecField
from stars.models import Star
from .models import Observatory, SpecFile


class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True


class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = single_file_clean(data, initial)
        return result


# ===========================================================================================
#  SPECFILE
# ===========================================================================================

class UploadSpectraDetailForm(forms.Form):
    #   File
    spectrumfile = MultipleFileField(label='Please select the spectra...')

    # merge_spectra_if_possible = forms.BooleanField(required=False)

    #   Add info provided by the user?
    add_info = forms.BooleanField(initial=False, required=False)

    #   File type
    filetype = forms.CharField(max_length=50, required=False)

    #   Target
    objectname = forms.CharField(max_length=50, required=False)
    ra = RAField(
        max_length=15,
        required=False,
        widget=forms.TextInput(attrs={'placeholder': '  h:m:s or d.d°'}),
    )
    dec = DecField(
        max_length=15,
        required=False,
        widget=forms.TextInput(attrs={'placeholder': '  ° : \' : \'\' or d.d°'}),
    )
    create_new_star = forms.BooleanField(initial=True, required=False)
    classification = forms.CharField(max_length=50, required=False)
    classification_type = forms.ChoiceField(
        choices=(
            ('SP', 'Spectroscopic'),
            ('PH', 'Photometric'),
        ),
        initial='PH',
        required=False,
    )

    #   Observatory
    observatory = forms.ModelChoiceField(
        queryset=Observatory.objects.all(),
        required=False,
    )
    observatory_name = forms.CharField(max_length=100, required=False)
    observatory_latitude = forms.FloatField(required=False)
    observatory_longitude = forms.FloatField(required=False)
    observatory_altitude = forms.FloatField(required=False)
    observatory_is_spacecraft = forms.BooleanField(required=False)

    #   Instrument and setup
    telescope = forms.CharField(max_length=200, required=False)
    instrument = forms.CharField(max_length=200, required=False)
    hjd = forms.FloatField(required=False)
    exptime = forms.FloatField(required=False)
    resolution = forms.FloatField(required=False)
    snr = forms.FloatField(required=False)
    observer = forms.CharField(max_length=50, required=False)

    #   Observing conditions
    wind_speed = forms.FloatField(required=False)
    wind_direction = forms.FloatField(required=False)
    seeing = forms.FloatField(required=False)
    airmass = forms.FloatField(required=False)

    #   Normalized
    normalized = forms.BooleanField(required=False)

    #   Barycentric Correction
    # barycor      = forms.FloatField(required=False)
    barycor_bool = forms.BooleanField(required=False, initial=True)

    #   Flux info
    fluxcal = forms.BooleanField(required=False)
    flux_units = forms.CharField(max_length=50, required=False)

    #   Master and/or decomposed spectrum
    master = forms.BooleanField(required=False)
    decomposed = forms.BooleanField(required=False)

    #   Note
    note = forms.CharField(
        widget=forms.Textarea(attrs={'cols': 70, 'rows': 10}),
        required=False,
    )


# class UploadSpecFileForm(forms.Form):
#     specfile_field = forms.FileField(
#         label='Select a spectrum',
#         widget=forms.ClearableFileInput(
#             attrs={'allow_multiple_selected': True}
#             )
#     )


class UploadRawSpecFileForm(forms.Form):
    """
        Upload form for spectroscopic raw data
    """

    system_name = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={'class': 'form_long'}),
        required=False,
    )

    system = forms.ModelMultipleChoiceField(
        label='Systems',
        queryset=Star.objects.all(),
        widget=forms.SelectMultiple(attrs={'class': 'form_long_extra'}),
        required=False,
    )

    specfile_date = forms.DateTimeField(
        label='Observation date',
        widget=forms.TextInput(attrs={'class': 'form_long'}),
        required=False,
    )

    specfile = forms.ModelMultipleChoiceField(
        label='Spectra',
        queryset=SpecFile.objects.all(),
        widget=forms.SelectMultiple(attrs={'class': 'form_long_extra'}),
        # required=True,
        required=False,
    )

    #   Raw file upload field
    raw_files = MultipleFileField(label='Raw files')


class PatchRawSpecFileForm(forms.Form):
    """
        Patch form for spectroscopic raw data
    """
    system_name_patch = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={'class': 'form_long'}),
        required=False,
    )

    system_patch = forms.ModelMultipleChoiceField(
        label='Systems',
        queryset=Star.objects.all(),
        widget=forms.SelectMultiple(attrs={'class': 'form_long_extra'}),
        required=False,
    )

    specfile_date_patch = forms.DateTimeField(
        label='Observation date',
        widget=forms.TextInput(attrs={'class': 'form_long'}),
        required=False,
    )

    specfile_patch = forms.ModelMultipleChoiceField(
        label='Spectra',
        queryset=SpecFile.objects.all(),
        widget=forms.SelectMultiple(attrs={'class': 'form_long_extra'}),
        required=True,
    )


class OrderField(forms.IntegerField):
    """
        Specific form field for the polynomial order
    """

    def validate(self, value):
        #   Use the parent's handling of integer fields
        super().validate(value)
        #   Add specific handling
        if value is not None and value > 15:
            raise forms.ValidationError("More than 15 orders are not supported")


class BinningField(forms.IntegerField):
    """
        Specific form field for the polynomial order
    """

    def validate(self, value):
        #   Use the parent's handling of integer fields
        super().validate(value)
        #   Add specific handling
        if value is not None and value > 100:
            raise forms.ValidationError("Binning of > 100 is not supported")
        # if value != None and value == 0:
        # raise forms.ValidationError("Binning of 0 makes no sense")


class SpectrumModForm(forms.Form):
    """
        Form to customize spectral plots (on the detail page)
    """
    normalize = forms.BooleanField(label="Normalize", required=False)
    order = OrderField(label="Polynomial order", required=False)
    binning = BinningField(label="Select a binning", required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.initial['order'] = 3
        self.initial['binning'] = 10


# ===========================================================================================
#  LICHT CURVES
# ===========================================================================================

class UploadLightCurveForm(forms.Form):
    lcfile = MultipleFileField(label='Select light curves')


# ===========================================================================================
#  OBSERVATORIES
# ===========================================================================================

class UpdateObservatoryForm(forms.Form):
    pk = forms.IntegerField(required=True)
    name = forms.CharField(max_length=50, required=True)
    short_name = forms.CharField(max_length=50, required=True)
    telescopes = forms.CharField(max_length=50, required=False)
    latitude = forms.FloatField(required=True)
    longitude = forms.FloatField(required=True)
    altitude = forms.FloatField(required=False)
    space_craft = forms.BooleanField(label="Space Craft", required=False)
    note = forms.CharField(max_length=150, required=False)
    url = forms.CharField(max_length=150, required=False)
    weatherurl = forms.CharField(max_length=150, required=False)

observations/templates/observations/lightcurve_detail.html
{% extends "base.html" %}
{% load static %}
{% load conversion_tags %}

{% block head %}

    {% include "bokeh.html" %}
    {% include "bokeh_widgets.html" %}
    <script type="text/javascript" src="{% static 'js/lightcurve_detail.js' %}"></script>
    <title>Light Curve: {{ lightcurve }}</title>

{% endblock %}


{% block headertitle %}Light Curve{% endblock %}


{% block content %}

    <div id="sidenav">
        <h2> All Lightcurves for <span class="nobreak">{{ lightcurve.star.name }}</span></h2>
        {% for inst, lightcurves in all_lightcurves.items %}
            <h3> {{ inst }} </h3>
            <ul>
                {% for lc in lightcurves %}
                    {% if lc.id == lightcurve.id %}
                        <li>
                            <a href={% url 'observations:lightcurve_detail' project.slug lc.id %} class="active"> {{ lc.hjd|floatformat:3 }}
                                - {{ lc.hjd|hjd2date }}</a></li>
                    {% else %}
                        <li>
                            <a href={% url 'observations:lightcurve_detail' project.slug lc.id %}> {{ lc.hjd|floatformat:3 }}
                                - {{ lc.hjd|hjd2date }}</a></li>
                    {% endif %}
                {% endfor %}
            </ul>
        {% endfor %}
    </div>

    <section class='data-section'>

        <div class="main-container-h border">

            {% if user.is_authenticated %}
                <i id="spectrumEditButton" class="material-icons button edit" title="edit"
                   spectrum_id={{ lightcurve.pk }}>edit</i>
            {% endif %}

            <div class='header-item'>
                <h3 id="nameField"> {{ lightcurve }}</h3>
            </div>

            <div class='header-item'>
                <p class="material-icons">star</p>
                <h3>
                    <a href={% url 'systems:star_detail' project.slug lightcurve.star.pk %}>{{ lightcurve.star.name }}</a>
                </h3>
            </div>


            <div class='header-item'>
                {% if lightcurve.valid %}
                    <i id="lightcurve-valid-icon" class="material-icons status-icon valid bold"
                       title='Good quality'></i>
                {% else %}
                    <i id="lightcurve-valid-icon" class="material-icons status-icon invalid bold"
                       title='Bad quality'></i>
                {% endif %}
                <h3> Valid</h3>
            </div>


        </div>

        <!--    <h3>Observing Information</h3> -->

        <div class="flex-data-container j-center">

            <div class="tag-container">
                <h3>Basic Data </h3>

                <div class="block">
                    <div class="block">
                        <table class='datatable'>
                            <tbody>
                            <tr>
                                <th>Target:</th>
                                <td class="mono">{{ lightcurve.objectname }}</td>
                            </tr>
                            <tr>
                                <th>Target Coord.:</th>
                                <td class="mono">{{ lightcurve.star.ra|dgr2hms }} {{ lightcurve.star.dec|dgr2dms }}</td>
                            </tr>
                            <tr>
                                <th>Obs. Coord.:</th>
                                <td class="mono">{{ lightcurve.ra|dgr2hms }} {{ lightcurve.dec|dgr2dms }}</td>
                            </tr>
                            <tr>
                                <th>HJD:</th>
                                <td class="mono">{{ lightcurve.hjd }}</td>
                            </tr>
                            <tr>
                                <th>Date:</th>
                                <td class="mono">{{ lightcurve.hjd|hjd2datetime }}</td>
                            </tr>
                            <tr>
                                <th>Instrument:</th>
                                <td class="mono">{{ lightcurve.instrument }} @ {{ lightcurve.telescope }}</td>
                            </tr>
                            <tr>
                                <th>Passband:</th>
                                <td class="mono">{{ lightcurve.passband }}</td>
                            </tr>
                            <tr>
                                <th>Observer:</th>
                                <td class="mono">{{ lightcurve.observer }}</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>

                    <div class="block">
                        <table class='datatable'>
                            <tbody>
                            <tr>
                                <th>Exposure:</th>
                                <td class="mono">{{ lightcurve.exptime|format_float_negative_na:'1|s' }}</td>
                            </tr>
                            <tr>
                                <th>Cadence:</th>
                                <td class="mono">{{ lightcurve.cadence|format_float_negative_na:'1|s' }}</td>
                            </tr>
                            <tr>
                                <th>Duration:</th>
                                <td class="mono">{{ lightcurve.duration|format_float_negative_na:'2|h' }}</td>
                            </tr>
                            <tr>
                                <th>Seeing:</th>
                                <td class="mono">{{ lightcurve.seeing|format_float_negative_na:'1|"' }}</td>
                            </tr>
                            <tr>
                                <th>Moon Illumination:</th>
                                <td class="mono">{{ lightcurve.moon_illumination|format_float_negative_na:'1|%' }} </td>
                            </tr>
                            <tr>
                                <th>Wind speed:</th>
                                <td class="mono">{{ lightcurve.wind_speed|format_float_negative_na:'1|km/s' }}</td>
                            </tr>
                            <tr>
                                <th>Wind direction:</th>
                                <td class="mono">{{ lightcurve.wind_direction|format_wind_direction }}</td>
                            </tr>
                            {% if lightcurve.get_weather_url != '' %}
                                <tr>
                                    <th>Weather link:</th>
                                    <td class="mono"><a target="_blank"
                                                        href="{{ lightcurve.get_weather_url }}"> {{ lightcurve.observatory.short_name }} </a>
                                    </td>
                                </tr>
                            {% else %}
                                <tr>
                                    <th>Weather link:</th>
                                    <td class="mono">NA</td>
                                </tr>
                            {% endif %}
                            </tbody>
                        </table>
                    </div>
                </div>


            </div>

            <div class="tag-container">
                <h3>Visibility</h3>
                <div class='block'>
                    {{ figures.visibility|safe }}
                </div>
            </div>

            <div class="tag-container">
                <h3>Light cuve files</h3>
                <ul>
                    <li>{{ lightcurve.filetype }}
                        <a href={% url 'observations-api:lightcurve_header' lightcurve.id %} class='showheader'
                           name='{{ lightcurve.filetype }}'>(header)</a>
                        {% if user.is_authenticated %}
                            <a href="{{ lightcurve.lcfile.url }}"><p class="material-icons inline-icon"
                                                                     title="Download">cloud_download</p></a>
                        {% endif %}
                    </li>
                </ul>


                <h3>
                    Note
                    {% if user.is_authenticated %}
                        (<i id="noteEditButton" class="material-icons button inline-icon" title="edit"
                            lightcurve_id={{ lightcurve.pk }}>edit</i>)
                    {% endif %}
                </h3>

                <div id="noteField">{{ lightcurve.note|linebreaks }}</div>

            </div>

        </div>

        <hr>

    </section>

    <section class='data-section'>


        <div class="flex-data-container">

            {% if figures.lc_time %}
                <!--    <div class="block w1100"> -->
                {{ figures.lc_time|safe }}
                <!--    </div> -->
            {% endif %}

        </div>

        <div>

            <form action="{% url "observations:lightcurve_detail" project.slug lightcurve.pk %}" method="get"
                  enctype="multipart/form-data">

                <tbody>
                <tr>
                    <td>Period (hours):</td>
                    <td><input type="number" name='period' step=0.00000000001 value={{ period }}></td>
                    <td>Phase bins size:</td>
                    <td><input type="number" name='binsize' min=0.0001 max=1 step=0.0001 value={{ binsize }}></td>
                    <td><input type="submit" value="phase lightcurve"/></td>
                </tr>
                </tbody>

            </form>

        </div>

        <div class="flex-data-container">

            {% if figures.lc_phase %}
                <!--    <div class="block w1100"> -->
                {{ figures.lc_phase|safe }}
                <!--    </div> -->
            {% endif %}

        </div>

        <hr>

    </section>

    <div id="headerWindow">
        <ul id="headerList">
        </ul>
    </div>

    {{ script|safe }}


    <!-- Div ect necessary for editing on page stuff with ajax -->
    <div id="noteEdit" title="Edit lightcurve Note">
        <textarea name="edit-message" id="edit-message" cols="80" rows="5"></textarea>
    </div>

    <div id="lightcurveEdit" title="Edit lightcurve">

        <ul>
            <li>
                <label for="lightcurve-valid">
                    <input type="checkbox" id="lightcurve-valid" lightcurve_id="{{ lightcurve.pk }}">
                    Valid </label>
            </li>

            <li>
                <label for="lightcurve-fluxunits"> Exposure Time:
                    <input id="lightcurve-exptime" type='text' size="100">
                </label>
            </li>

        </ul>
    </div>

{% endblock %}

observations/templates/observations/observatory_list.html
{% extends "base.html" %}
{% load static %}

{% block head %}

    {% include "datatables.html" %}
    <script type="text/javascript" src="{% static 'js/observatory_list.js' %}"></script>
    <title>Observatories</title>

{% endblock %}

{% block headertitle %} Observatories {% endblock %}

{% block content %}

    <i display="none" id="project-pk" project={{ project.pk }}></i>

    <section>

        <table id="observatorytable" class="fullwidth">
            <thead>
            <tr>
                <th>Name</th>
                <th>Telescopes</th>
                <th>Latitude (deg)</th>
                <th>Longitude (deg)</th>
                <th>Altitude (m)</th>
                <th>Space Craft</th>
                <th>Note</th>
                <th>Action <i class="observatoryAddButton material-icons button add" title="Add new">add_box</i></th>
            </tr>
            </thead>
            <tfoot>
            <tr>
                <th>Name</th>
                <th>Telescopes</th>
                <th>Latitude (deg)</th>
                <th>Longitude (deg)</th>
                <th>Altitude (m)</th>
                <th>Space Craft</th>
                <th>Note</th>
                <th>Action <i class="observatoryAddButton material-icons button add" title="Add new">add_box</i></th>
            </tr>
            </tfoot>
        </table>


    </section>


    <div id="observatoryEdit">
        <form action="{% url "observations:observatory_list" project.slug %}" method="post"
              enctype="multipart/form-data" class="" id="update-obs-form">
            {% csrf_token %}
            {{ update_obs_form.pk.as_hidden }}
            <ul>
                <li><p class="label">Name:</p> {{ update_obs_form.name }}</li>
                <li><p class="label">Short Name:</p> {{ update_obs_form.short_name }}</li>
                <li><p class="label">Telescopes:</p> {{ update_obs_form.telescopes }}</li>
                <li><p class="label">Latitude (deg):</p> {{ update_obs_form.latitude }}</li>
                <li><p class="label">Longitude (deg):</p> {{ update_obs_form.longitude }}</li>
                <li><p class="label">Altitude (meter):</p> {{ update_obs_form.altitude }}</li>
                <li><p class="label">space craft:</p> {{ update_obs_form.space_craft }}</li>
                <li><p class="label">Note:</p> {{ update_obs_form.note }}</li>
                <li><p class="label">Website:</p> {{ update_obs_form.url }}</li>
                <li><p class="label">Weather url:</p> {{ update_obs_form.weatherurl }}</li>
                <li><input type="submit" value="Update"></li>
            </ul>
        </form>
    </div>

{% endblock %}