AOTS/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
# from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView, TemplateView
from rest_framework import routers

from stars import views as star_views
from stars.api.views import ProjectViewSet

router = routers.DefaultRouter()
router.register(r'projects', ProjectViewSet)

urlpatterns = [
                  path('', RedirectView.as_view(pattern_name='projects')),
                  path(
                      "robots.txt",
                      TemplateView.as_view(
                          template_name="robots.txt",
                          content_type="text/plain",
                      ),
                  ),

                  path(
                      'w/documentation/',
                      TemplateView.as_view(
                          template_name='documentation.html'
                      )
                  ),
                  path(
                      'w/projects/',
                      star_views.project_list,
                      name='projects',
                  ),
                  path(
                      'w/<slug:project>/',
                      RedirectView.as_view(pattern_name='dash:dashboard')
                  ),
                  path(
                      'w/<slug:project>/systems/',
                      include('stars.urls', namespace='systems')
                  ),
                  path(
                      'w/<slug:project>/observations/',
                      include(
                          'observations.urls',
                          namespace='observations'
                      )
                  ),
                  path(
                      'w/<slug:project>/dash/',
                      include('dash.urls', namespace='dash')
                  ),
                  path(
                      'w/<slug:project>/observations/',
                      RedirectView.as_view(
                          pattern_name='observations:observatory_list'
                      )
                  ),
                  path(
                      'w/<slug:project>/analysis/',
                      include('analysis.urls', namespace='analysis')
                  ),
                  path(
                      'w/<slug:project>/dashboard/',
                      RedirectView.as_view(pattern_name='dash:dashboard')
                  ),

                  path('api/', include(router.urls), name='project-api'),
                  path(
                      'api/systems/',
                      include("stars.api.urls", namespace='systems-api')
                  ),
                  path(
                      'api/observations/',
                      include(
                          "observations.api.urls",
                          namespace='observations-api'
                      )
                  ),
                  path(
                      'api/analysis/',
                      include(
                          "analysis.api.urls",
                          namespace='analysis-api'
                      )
                  ),
                  path(
                      'users/',
                      include(
                          "users.urls",
                          namespace='users'
                      )
                  ),

                  path(r'admin/', admin.site.urls),

                  # path('', RedirectView.as_view(url='/stars/stars/', permanent=False)),
                  # path('stars/', include('stars.urls', namespace='stars'), name='stars'),
                  # path('observations/', include('observations.urls'), name='observations'),
                  # path('analysis/', include('analysis.urls'), name='analysis'),

                  # path(r'api/stars/', include("stars.api.urls"), name='stars-api'),
                  # path(r'api/observations/', include("observations.api.urls"), name='observations-api'),
                  # path(r'api/analysis/', include("analysis.api.urls"), name='analysis-api'),

                  # path(r'^login/$', auth_views.login, name='login'),
                  # path(r'^logout/$', auth_views.logout, {'next_page': '/stars/stars'}, name='logout'),
                  # path(r'^change-password/$', auth_views.password_change, name='change-pwd'),
                  # path(r'^password-change-done/$', auth_views.password_change_done, name='password_change_done'),

                  # include all relevant user login/logout stuff. This includes:
                  #  accounts/login/ [name='login']
                  #  accounts/logout/ [name='logout']
                  #  accounts/password_change/ [name='password_change']
                  #  accounts/password_change/done/ [name='password_change_done']
                  #  accounts/password_reset/ [name='password_reset']
                  #  accounts/password_reset/done/ [name='password_reset_done']
                  #  accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
                  #  accounts/reset/done/ [name='password_reset_complete']
                  path('accounts/', include('django.contrib.auth.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

analysis/api/urls.py
from django.urls import include, re_path, path
from rest_framework import routers
from analysis.api.views import getRVCurvePath
from .views import (
    ParameterViewSet, DatasetViewSet, MethodViewSet, processDataSet, SEDViewSet, RVcurveViewSet, bulkUploadRVcurves,
)

app_name = 'analysis-api'

router = routers.DefaultRouter()
router.register(r'methods', MethodViewSet)
router.register(r'datasets', DatasetViewSet)
router.register(r'parameters', ParameterViewSet)
router.register(r'seds', SEDViewSet)
router.register(r'rvcurves', RVcurveViewSet)

urlpatterns = [
    ##url(r'^datasets$', DatasetListAPIView.as_view(), name='dataset_list'),
    re_path(r'^', include(router.urls)),
    re_path(r'^datasets/(?P<pk>[\w-]+)/process/',
            processDataSet,
            name='process_dataset',
            ),
    path(
        'api-rvcurve-upload/',
        bulkUploadRVcurves,
        name='api-spec-upload',
    ),
    path(
        'rvcurves/<int:rvcurve_pk>/path/',
        getRVCurvePath,
        name='rvcurve_path',
    ),
]

analysis/urls.py
from django.urls import path

from . import views

app_name = 'analysis'
urlpatterns = [
    ## Deprecated, will be removed in future ##
    path('datasets/', views.dataset_list, name='dataset_list'),
    path(
        'datasets/<int:dataset_id>/',
        views.dataset_detail,
        name='dataset_detail'
    ),
    path('methods', views.method_list, name='method_list'),
    ##

    path('rvcurves/', views.rvcurve_list, name='rvcurve_list'),
    path(
        'rvcurves/<int:rvcurve_id>/',
        views.rvcurve_detail,
        name='rvcurve_detail'
    ),

    path('seds/', views.SED_list, name='SED_list'),
    path(
        'seds/<int:sed_id>/',
        views.SED_detail,
        name='SED_detail'
    ),

    path('plotter', views.parameter_plotter, name='parameter_plotter'),

]

dash/urls.py
from django.urls import path

from . import views

app_name = 'dash'
urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard')
]

stars/urls.py
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path
from django.views.generic.base import RedirectView

from . import views

app_name = 'systems'
urlpatterns = [
    path('stars/', views.star_list, name='star_list'),
    path('stars/<int:star_id>', views.star_detail, name='star_detail'),
    path('stars/<int:star_id>/edit', views.star_edit, name='star_edit'),
    path('tags/', views.tag_list, name='tag_list'),
    path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")),
    ),
]

analysis/models/parameters.py
from django.db import models
from django.db.models.signals import pre_delete, post_delete, post_save, pre_save
from django.dispatch import receiver

from analysis.auxil import parameter_derivation
from stars.models import Star
from .datasource import DataSource, AverageDataSource
# -- all constants are the roud_value function are imported from default values
from .default_values import *


def combine_parameter_name(name, component):
    if component in [1, 2]:
        return name + '_' + str(component)
    else:
        return name


class ParameterManager(models.Manager):
    """
    Custom manager for Parameter class to provide sorting of the parameters in a more
    sensible fashion than alphabetical (provides standard order options)
    """

    def order_by(self, *args, **kwargs):
        super(ParameterManager, self).get_query_set().order_by(*args, **kwargs)

    def order(self, *args, **kwargs):
        parameters = self.get_queryset().all()
        sorted_results = sorted(parameters, key=lambda t: t.order())
        return sorted_results


class Parameter(models.Model):
    """
    A simple parameter belonging to a parameter set
    The parameter consists of a value, error and unit
    """

    # -- provide custom sorting options that make sense
    objects = ParameterManager()

    def order(self):
        return parameter_order(self.name)

    # -- A parameter belongs to a system, and will be deleted if the system
    #   is deleted.
    star = models.ForeignKey(Star, on_delete=models.CASCADE, blank=True, null=True)

    # -- a parameter can belong to a dataset or datatable, but doesn't have too.
    #   However, if it does belong to one, it has to be removed if the
    #   datasource is removed.
    data_source = models.ForeignKey(DataSource, on_delete=models.CASCADE, blank=True, null=True)

    # -- name of the variable measured in this parameter
    name = models.CharField(max_length=50)

    # -- component the parameter belongs to
    component = models.IntegerField(
        choices=COMPONENT_CHOICES,
        default=SYSTEM)

    # -- add component behind name if component is primary or secondary
    cname = models.CharField(max_length=52, default='')

    value = models.FloatField(default=0.0)

    # -- errors are stored as upper and lower error, and error function is
    #   provided to return the average error in 1 value.
    #   the error field can also be directly set and will populate the
    #   error_l and _u field with the save value.
    error_l = models.FloatField(default=0.0)  # lower error
    error_u = models.FloatField(default=0.0)  # upper error

    @property
    def error(self):
        # return the error based on lower and upper error
        return (self.error_l + self.error_u) / 2.0

    @error.setter
    def error(self, val):
        # set  lower and upper error to the error value
        self.error_l = val
        self.error_u = val

    # -- unit in which this variable is measured
    unit = models.CharField(max_length=50)

    # -- valid setting to indicate wether or not this parameter is trustworthy
    valid = models.BooleanField(default=True)

    # -- set average=True to indicate this parameter contains the average
    #   of all measurements of this variable for this star. This average
    #   parameter is automatically created and updated upon saving a parameter
    average = models.BooleanField(default=False)

    # -- Rounded value and errors
    def rvalue(self):
        return round_value(self.value, self.name, self.error)

    def rerror(self):
        return round_value(self.error, self.name, self.error)

    def rerror_l(self):
        return round_value(self.error_l, self.name, self.error_l)

    def rerror_u(self):
        return round_value(self.error_u, self.name, self.error_u)

    # -- representation of self
    def __str__(self):
        try:
            ds = self.data_source.name[0:10]
        except DataSource.DoesNotExist:
            ds = ''
        return "{} = {} +- {} {} -{}- ({})".format(self.cname, self.rvalue(), self.rerror(),
                                                   self.unit, 'V' if self.valid else 'F', ds)


class DerivedParameter(Parameter):
    """
    Subtype of an average parameter that is derived based on other parameters
    """

    source_parameters = models.ManyToManyField(Parameter, blank=True, related_name='derived_parameters')

    def create(self):
        success = parameter_derivation.find_parameters(self)
        # try:
        # names, components = parameter_derivation.find_parameters(self)
        # for n, c in zip(names, components):
        # p = Parameter.objects.get(star__exact=self.star, name__exact=n,
        # component__exact=c, average__exact=True)
        # self.source_parameters.add(p)

        # except Exception as e:
        # print (e)

    def update(self):
        try:
            parameter_derivation.calculate(self)
            self.average = True

            return True
        except Exception as e:
            print(e)

            return False

    # -- representation of self
    def __str__(self):
        return "{} = {} +- {} {} -{}- ({})".format(self.cname, self.rvalue(), self.rerror(),
                                                   self.unit, 'V' if self.valid else 'F', 'DRVD')


# ======================================================================================
# cname parameter handling
# ======================================================================================

@receiver(pre_save, sender=Parameter)
@receiver(pre_save, sender=DerivedParameter)
def set_cname(sender, **kwargs):
    """
    When a parameter is created or modified, update the cname based on the
    parameter name and the component number:
    cname = name + _ + component if component is 1 or 2.
    """
    if kwargs.get('raw', False):
        return

    param = kwargs['instance']
    param.cname = combine_parameter_name(param.name, param.component)


# ======================================================================================
# AVERAGE parameter handling
# ======================================================================================

def calculate_average(params):
    """
    Calculates the average value and error based on the given parameters
    params needs to be a queryset
    """
    values = np.array(params.values_list('value', flat=True))

    # -- work with 1D average errors
    errors_l = np.array(params.values_list('error_l', flat=True))
    errors_u = np.array(params.values_list('error_u', flat=True))
    errors = (errors_l + errors_u) / 2.0

    # -- if the error is zero, assume a 10% error when calculating the average,
    #   if also the value is zero, assume an error of 1.
    errors = np.where(errors == 0, values / 10., errors)
    errors = np.where(errors == 0, 1., errors)

    error = np.sqrt(np.sum(errors ** 2)) / len(errors)

    return np.average(values, weights=1. / errors), error


@receiver(post_delete, sender=Parameter)
@receiver(post_save, sender=Parameter)
def average_parameter_bookkeeping(sender, **kwargs):
    """
    Create, update and delete average parameters when parameters
    are added, updated, or deleted.
    """

    if kwargs.get('raw', False):
        return

    param = kwargs['instance']

    try:
        s = param.star
    except Star.DoesNotExist:
        # -- this star is being deleted along with all related parameters, do nothing
        return

    if not param.average:
        p = Parameter.objects.filter(name__exact=param.name,
                                     component__exact=param.component,
                                     star__exact=param.star,
                                     valid__exact=True,
                                     average__exact=False)

        if len(p) == 0:
            # There are no parameters left: delete the average
            try:
                ap = Parameter.objects.get(name__exact=param.name,
                                           component__exact=param.component,
                                           star__exact=param.star,
                                           valid__exact=True,
                                           average__exact=True)
                ap.delete()
            except Exception as e:
                pass

        else:
            # We need to update the average, or possible create a new one
            value, error = calculate_average(p)

            try:
                ap = Parameter.objects.get(name__exact=param.name,
                                           component__exact=param.component,
                                           star__exact=param.star,
                                           valid__exact=True,
                                           average__exact=True)
                ap.value = value
                ap.error = error
                ap.save()

            except Parameter.DoesNotExist:

                # -- first get the datasource containing the average parameters
                try:
                    ds = AverageDataSource.objects.get(project__exact=param.star.project)
                except AverageDataSource.DoesNotExist:
                    ds = AverageDataSource.objects.create(name='AVG', project=param.star.project)

                ap = Parameter.objects.create(star=param.star,
                                              name=param.name,
                                              component=param.component,
                                              value=value,
                                              error=error,
                                              unit=param.unit,
                                              average=True,
                                              valid=True,
                                              data_source=ds)


# ======================================================================================
# DERIVED parameter handling

analysis/templates/analysis/SED_list.html
{% extends "base.html" %}
{% load static %}

{% block head %}

    {% include "datatables.html" %}
    <script type="text/javascript" src="{% static 'js/sed_list.js' %}"></script>

    <title>SEDs</title>

{% endblock %}

{% block headertitle %} SEDs {% endblock %}

{% block content %}

    <i display="none" id="project-pk" project={{ project.pk }}></i>

    <i class="material-icons button filter" id="filter-dashboard-button">filter_list</i>

    <div id="filter-dashboard">

        <form method="get" action="/analysis/" class="table-filter" id="filter-form">
            <h3 class="center"> Filter SEDs </h3>

            <div class="table-filter-item">
                <p class="filter-label">Target:</p>
                <input class="filter-input" id="filter_target" type="text" placeholder="identifier">
            </div>

            <input type="submit" class="button filter" id="submit-search" value="Apply">
        </form>

    </div>

    <section>

        <table id="sedstable" class="fullwidth">
            <thead>
            <tr>
                {% if user.is_authenticated %}
                    <th>
                        <i id="select-all" class="material-icons button select" title="Select/Deselect All">check_box_outline_blank</i>
                    </th>
                {% endif %}
                <th>Effective Temperature T<sub>eff</sub></th>
                <th>System</th>
                <th>Surface Gravity log(g)</th>
                <th>Angular diameter log(ϴ)</th>
                <th>Metallicity</th>
                <th>Color Excess</th>
            </tr>
            </thead>
            <tfoot>
            <tr>
                {% if user.is_authenticated %}
                    <th></th>
                {% endif %}
                <th>Effective Temperature T<sub>eff</sub></th>
                <th>System</th>
                <th>Surface Gravity log(g)</th>
                <th>Angular diameter log(ϴ)</th>
                <th>Metallicity</th>
                <th>Color Excess</th>
            </tr>
            </tfoot>
        </table>

    </section>

    <div id="uploadseds">
        <div class="ui-controlgroup-horizontal">
            <form action="{% url "analysis:SED_list" project.slug %}" method="post"
                  enctype="multipart/form-data" class="upload" id="system-upload-form">
                <h3> Add new SEDs </h3>
                {% if user.is_authenticated %}
                    {% csrf_token %}
                    {% if upload_form.non_field_errors %}
                        <p>{{ upload_form.non_field_errors }}</p>
                    {% endif %}

                    <p>
                        {{ upload_form.sourcefile.errors }}
                        {{ upload_form.sourcefile }}
                    </p>

                    <!--       <input id="system-add-upload-button" type="submit" class="material-icons button" value="file_upload"/> -->
                    <input type="submit" class="upload-button" value="Upload SED File"/>
                {% else %}
                    <p> Log in to upload SEDs! </p>
                {% endif %}
            </form>
        </div>
        <a disabled {#  href="/media/docs/Bulk_system_example.csv" #}><p class="add-system-csv-example">Example .fits file (coming soon!)</p>
        </a>
    </div>
{% endblock %}

analysis/templates/analysis/dataset_detail.html
{% extends "base.html" %}
{% load static %}
{% load conversion_tags %}

{% block head %}

    {% include "bokeh.html" %}
    <script type="text/javascript" src="{% static 'js/dataset_detail.js' %}"></script>
    <title>Dataset: {{ dataset.star.name }} - {{ dataset.method.name }}</title>

{% endblock %}


{% block headertitle %}Dataset: {{ dataset.star.name }} - {{ dataset.method.name }} {% endblock %}


{% block content %}

    <i display="none" id="project-pk" project={{ project.pk }}></i>

    <div id="sidenav">
        <h2> Related datasets </h2>

        {% if related_datasets %}
            <div>
                <h3 title="Other datasets for the same star"> {{ dataset.star.name }} </h3>
                    <ul>
                        {% for d in related_datasets %}
                            {% if d.id == dataset.id %}
                                <li>
                                    <a href={% url 'analysis:dataset_detail' project.slug d.pk %} class="active">-- {{ d.method.name }}
                                        --</a>
                                </li>
                            {% else %}
                                <li>
                                    <a href={% url 'analysis:dataset_detail' project.slug d.pk %}>{{ d.method.name }}</a>
                                </li>
                            {% endif %}
                        {% endfor %}
                    </ul>
            </div>
        {% endif %}

        {% if related_stars %}
            <div>
                <h3 title="Other stars with same dataset type"> {{ dataset.method.name }} </h3>
                    <ul>
                        {% for d in related_stars %}
                            {% if d.id == dataset.id %}
                                <li>
                                    <a href={% url 'analysis:dataset_detail' project.slug d.pk %} class="active">-- {{ d.star.name }}
                                        --</a>
                                </li>
                            {% else %}
                                <li>
                                    <a href={% url 'analysis:dataset_detail' project.slug d.pk %}>{{ d.star.name }}</a>
                                </li>
                            {% endif %}
                        {% endfor %}
                    </ul>
            </div>
        {% endif %}

    </div>

    <section class='data-section'>

        <div class="main-container-h border">

            {% if user.is_authenticated %}
                <i id="nameEditButton" class="material-icons button edit" title="edit name" dataset_id={{ dataset.pk }}>edit</i>
            {% endif %}

            <div class='header-item'>
                <h3 id="nameField"> {{ dataset.name }}</h3>
            </div>

            <div class='header-item'>
                <p class="material-icons">star</p>
                <h3><a href={% url 'systems:star_detail' project.slug dataset.star.pk %}>{{ dataset.star.name }}</a>
                </h3>
            </div>

            <div class='header-item'>
                <p class="material-icons">build</p>
                <h3>{{ dataset.method.name }}</h3>
            </div>

            <div class='header-item'>
                <p class="material-icons">book</p>
                <h3><a target="_blank" href="{{ dataset.get_reference_url }}">{{ dataset.reference }}</a></h3>
            </div>

            <div class='header-item'>
                <input type="checkbox" id="dataset-valid-{{ dataset.pk }}" {% if dataset.valid %}
                       checked="checked" {% endif %} onchange='toggleDatasetValid(this);' dataset_id="{{ dataset.pk }}"
                        {% if not user.is_authenticated %} disabled {% endif %}>
                <h3> Valid </h3>
            </div>


        </div>

        <div class="flex-data-container j-center">

            <div class="main-container border maxw50 minw800">
                <!--zoom_out_map all_out fullscreen-->
                <div class='block'>
                    {{ fit|safe }}
                </div>

                <div class='block'>
                    {{ oc|safe }}
                </div>

            </div>


            <div class="main-container maxw50 stretch">

                <div class="main-container border ">
                    <h3>Parameters</h3>

                    {% if user.is_authenticated %}
                        <i id="switchParameterComponentButton" class="material-icons button edit"
                           title="Switch primary/secondary">cached</i>
                    {% endif %}

                    <table class="paramtable">
                        <thead>
                        <tr>
                            <th>Parameter</th>
                            <th>Value</th>
                            <th>Error</th>
                            <th>Valid</th>
                        </tr>
                        </thead>
                        <tbody class='mono'>
                        {% if dataset.parameter_set.all %}
                            {% for p in dataset.parameter_set.order %}
                                <tr>
                                    <th>{{ p.cname }} ({{ p.unit }})</th>
                                    <td>{{ p.rvalue }}</td>
                                    <td>{{ p.rerror }}</td>
                                    <td><input type="checkbox" id="cb-parameter-valid-{{ p.pk }}" {% if p.valid %}
                                               checked="checked" {% endif %} onchange='toggleParameterValid(this);'
                                               parameter_id="{{ p.pk }}"
                                            {% if not user.is_authenticated %} disabled {% endif %}></td>
                                </tr>
                            {% endfor %}
                        {% else %}
                            <tr id="tr-novaluesyet">
                                <td colspan="4">No data available</td>
                            </tr>
                        {% endif %}
                        </tbody>
                    </table>
                </div>

                <div class="main-container border">
                    <h3>Notes</h3>
                    {% if user.is_authenticated %}
                        <i id="noteEditButton" class="material-icons button edit" title="edit note"
                           dataset_id={{ dataset.pk }}>edit</i>
                    {% endif %}
                    <div id="noteField">
                        {{ dataset.note|linebreaks }}
                    </div>
                </div>

                <div class="main-container border">
                    <h3>Meta data</h3>
                    <table class="metatable">
                        <tr>
                            <th>Added by</th>
                            <td>{{ dataset.history.earliest.history_user.first_name }} {{ dataset.history.earliest.history_user.last_name }}</td>
                        </tr>
                        <tr>
                            <th>Added on</th>
                            <td>{{ dataset.history.earliest.history_date }}</td>
                        </tr>
                        <tr>
                            <th>Last modified</th>
                            <td>{{ dataset.history.latest.history_date }}</td>
                        </tr>
                        <tr>
                            <th>Modified by</th>
                            <td id=modified_by>{{ dataset.last.history_user.username }}</td>
                        </tr>
                    </table>
                </div>

            </div>


        </div>

        <hr>

    </section>

    <section class='data-section'>

        {% if hist.len > 0 %}
            <h3> Parameter distribution </h3>

            <div class="flex-data-container j-center">
                {% for fig in hist %}

                    <div class="block">
                        {{ fig|safe }}
                    </div>

                {% endfor %}
            </div>
        {% endif %}

    </section>

    <div id="noteEdit">
        <textarea name="edit-note" id="edit-note" cols="80" rows="5"></textarea>
    </div>

    <div id="nameEdit">
        <textarea name="edit-name" id="edit-name" cols="80" rows="2"></textarea>
    </div>

    {{ script|safe }}

{% endblock %}

analysis/templates/analysis/parameter_plotter.html
{% extends "base.html" %}
{% load static %}
{% load conversion_tags %}

{% block head %}

    {% include "bokeh.html" %}
    <!--    <script type="text/javascript" src="{% static 'js/dataset_detail.js' %}"></script> -->
    <title>Analysis: Parameter plotter</title>

{% endblock %}


{% block headertitle %} Analysis: Parameter plotter {% endblock %}


{% block content %}

    <i display="none" id="project-pk" project={{ project.pk }}></i>

    <section class='data-section'>

        <div class="flex-data-container j-center">

            <div class="main-container maxw50 stretch">

                <div class="main-container border">
                    <h3> Plot Setup</h3>

                    <form action="{% url "analysis:parameter_plotter" project.slug %}" method="get">

                        <table>
                            <tbody>
                            {% for field in form %}
                                <tr>
                                    <th>{{ field.label_tag }}</th>
                                    <td>
                                        {{ field }}
                                    <td>
                                    <td style="color:red;">
                                        {{ field.errors }}
                                    <td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>

                        <input type="submit" value="Update Figure"/>
                    </form>

                </div>

                <div class="main-container border">
                    <h3>Statistics</h3>

                    <p> {{ statistics }} </p>

                </div>

            </div>

            <div class="main-container border minw800">
                {{ figure|safe }}
            </div>

        </div>

    </section>

    {{ script|safe }}

{% endblock %}