AOTS/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
# from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView, TemplateView
from rest_framework import routers

from stars import views as star_views
from stars.api.views import ProjectViewSet

router = routers.DefaultRouter()
router.register(r'projects', ProjectViewSet)

urlpatterns = [
                  path('', RedirectView.as_view(pattern_name='projects')),
                  path(
                      "robots.txt",
                      TemplateView.as_view(
                          template_name="robots.txt",
                          content_type="text/plain",
                      ),
                  ),

                  path(
                      'w/documentation/',
                      TemplateView.as_view(
                          template_name='documentation.html'
                      )
                  ),
                  path(
                      'w/projects/',
                      star_views.project_list,
                      name='projects',
                  ),
                  path(
                      'w/<slug:project>/',
                      RedirectView.as_view(pattern_name='dash:dashboard')
                  ),
                  path(
                      'w/<slug:project>/systems/',
                      include('stars.urls', namespace='systems')
                  ),
                  path(
                      'w/<slug:project>/observations/',
                      include(
                          'observations.urls',
                          namespace='observations'
                      )
                  ),
                  path(
                      'w/<slug:project>/dash/',
                      include('dash.urls', namespace='dash')
                  ),
                  path(
                      'w/<slug:project>/observations/',
                      RedirectView.as_view(
                          pattern_name='observations:observatory_list'
                      )
                  ),
                  path(
                      'w/<slug:project>/analysis/',
                      include('analysis.urls', namespace='analysis')
                  ),
                  path(
                      'w/<slug:project>/dashboard/',
                      RedirectView.as_view(pattern_name='dash:dashboard')
                  ),

                  path('api/', include(router.urls), name='project-api'),
                  path(
                      'api/systems/',
                      include("stars.api.urls", namespace='systems-api')
                  ),
                  path(
                      'api/observations/',
                      include(
                          "observations.api.urls",
                          namespace='observations-api'
                      )
                  ),
                  path(
                      'api/analysis/',
                      include(
                          "analysis.api.urls",
                          namespace='analysis-api'
                      )
                  ),
                  path(
                      'users/',
                      include(
                          "users.urls",
                          namespace='users'
                      )
                  ),

                  path(r'admin/', admin.site.urls),

                  # path('', RedirectView.as_view(url='/stars/stars/', permanent=False)),
                  # path('stars/', include('stars.urls', namespace='stars'), name='stars'),
                  # path('observations/', include('observations.urls'), name='observations'),
                  # path('analysis/', include('analysis.urls'), name='analysis'),

                  # path(r'api/stars/', include("stars.api.urls"), name='stars-api'),
                  # path(r'api/observations/', include("observations.api.urls"), name='observations-api'),
                  # path(r'api/analysis/', include("analysis.api.urls"), name='analysis-api'),

                  # path(r'^login/$', auth_views.login, name='login'),
                  # path(r'^logout/$', auth_views.logout, {'next_page': '/stars/stars'}, name='logout'),
                  # path(r'^change-password/$', auth_views.password_change, name='change-pwd'),
                  # path(r'^password-change-done/$', auth_views.password_change_done, name='password_change_done'),

                  # include all relevant user login/logout stuff. This includes:
                  #  accounts/login/ [name='login']
                  #  accounts/logout/ [name='logout']
                  #  accounts/password_change/ [name='password_change']
                  #  accounts/password_change/done/ [name='password_change_done']
                  #  accounts/password_reset/ [name='password_reset']
                  #  accounts/password_reset/done/ [name='password_reset_done']
                  #  accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
                  #  accounts/reset/done/ [name='password_reset_complete']
                  path('accounts/', include('django.contrib.auth.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

analysis/urls.py
from django.urls import path

from . import views

app_name = 'analysis'
urlpatterns = [
    ## Deprecated, will be removed in future ##
    path('datasets/', views.dataset_list, name='dataset_list'),
    path(
        'datasets/<int:dataset_id>/',
        views.dataset_detail,
        name='dataset_detail'
    ),
    path('methods', views.method_list, name='method_list'),
    ##

    path('rvcurves/', views.rvcurve_list, name='rvcurve_list'),
    path(
        'rvcurves/<int:rvcurve_id>/',
        views.rvcurve_detail,
        name='rvcurve_detail'
    ),

    path('seds/', views.SED_list, name='SED_list'),
    path(
        'seds/<int:sed_id>/',
        views.SED_detail,
        name='SED_detail'
    ),

    path('plotter', views.parameter_plotter, name='parameter_plotter'),

]

observations/urls.py
from django.urls import path

from . import views

app_name = 'observations'
urlpatterns = [
    #   Spectra
    path('spectra/', views.spectra_list, name='spectra_list'),
    path(
        'spectra/<int:spectrum_id>/',
        views.spectrum_detail,
        name='spectrum_detail',
    ),
    path('spectra/upload', views.add_spectra, name='spectra_upload'),
    #   SpecFiles
    path('specfiles/', views.specfile_list, name='specfile_list'),
    #   RawSpecFiles
    path('rawspecfiles/', views.rawspecfile_list, name='rawspecfile_list'),
    #   Lightcurves
    path('lightcurves/', views.lightcurve_list, name='lightcurve_list'),
    path(
        'lightcurves/<int:lightcurve_id>/',
        views.lightcurve_detail,
        name='lightcurve_detail',
    ),
    #   Observatories
    path('observatories/', views.observatory_list, name='observatory_list'),
]

stars/urls.py
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path
from django.views.generic.base import RedirectView

from . import views

app_name = 'systems'
urlpatterns = [
    path('stars/', views.star_list, name='star_list'),
    path('stars/<int:star_id>', views.star_detail, name='star_detail'),
    path('stars/<int:star_id>/edit', views.star_edit, name='star_edit'),
    path('tags/', views.tag_list, name='tag_list'),
    path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")),
    ),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="{% static 'css/base.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/fontawesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/fontawesome_regular.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/fontawesome_solid.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/jquery-ui.css' %}" rel="stylesheet" type="text/css">
    <link rel="icon" href="{% static 'favicon.ico' %}">

    <script
            src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
            crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'js/base_js.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>

    {% block head %}{% endblock %}
</head>

<body>

<div class="page-wrap-base">
    <nav>
        <div class="nav_bar" id="mainNavBar">
          <a class="logo" href="/w/projects">
        <!--   <img src={% static "images/aotslogo.png" %}>-->
              AOTS
          </a>
<!--           &mdash; -->
          <a class="title_line">{{ project.name }}<i class="site_title">  &mdash; {% block headertitle %}{% endblock %}</i></a>
          <div class="float_right">
            <a href="/" id="projects_a">
              <i class="fa-solid fa-diagram-project"></i>
              Projects
            </a>
            <a href={% url 'dash:dashboard' project.slug %} id="dashboard_a">
              <i class="fa-solid fa-table-columns"></i>
              Dashboard
            </a>
            <div class="nav_dropdown" id="system_dropdown">
              <button class="drop_button">
                <i class="fa-solid fa-star"></i>
                Systems
                <i class="fa fa-caret-down"></i>
              </button>
              <div class="nav_dropdown-content">
                <a href={% url 'systems:star_list' project.slug %}>System list</a>
                <a href={% url 'systems:tag_list' project.slug %}>Tags</a>
              </div>
            </div>
            <div class="nav_dropdown" id="observation_dropdown">
              <button class="drop_button">
                <i class="fa-solid fa-binoculars"></i>
                Observations
                <i class="fa fa-caret-down"></i>
              </button>
              <div class="nav_dropdown-content">
                  <div class="unfold" >
                    <button class="unfold_button">Spectra
                      <i class="fa fa-caret-right" id="caretRight"></i>
                    </button>
                    <div class="unfold-content">
                      <a href={% url 'observations:spectra_list' project.slug %}>Overview</a>
                      <a href={% url 'observations:spectra_upload' project.slug %}>Upload</a>
                      <a href={% url 'observations:specfile_list' project.slug %}>File list</a>
                      <a href={% url 'observations:rawspecfile_list' project.slug %}>Raw data</a>
                    </div>
                  </div>
                <a href={% url 'observations:lightcurve_list' project.slug %}>Light Curves</a>
                <a href={% url 'observations:observatory_list' project.slug %}>Observatories</a>
              </div>
            </div>
            <div class="nav_dropdown" id="analysis_dropdown">
              <button class="drop_button">
                <i class="fa-solid fa-chart-line"></i>
                Analysis
                <i class="fa fa-caret-down"></i>
              </button>
              <div class="nav_dropdown-content">
                <a href={% url 'analysis:rvcurve_list' project.slug %}>RV Curves</a>
                <a href={% url 'analysis:SED_list' project.slug %}>SEDs</a>
              </div>
            </div>
            <a href="/w/documentation">
              <i class="fa-solid fa-book"></i>
              Guides
            </a>
            {% if user.is_authenticated %}
                <div class="nav_dropdown" id="user_dropdown">
                  <button class="drop_button active">
                    <i class="fa-solid fa-user"></i>
                    {{ user }}
                    <i class="fa fa-caret-down"></i>
                  </button>
                  <div class="nav_dropdown-content">
                    <a href="/users/you">View Profile</a>
                    <a href="/accounts/password_change">Change password</a>
                    <a href="/accounts/logout">Log Out</a>
                  </div>
                </div>
            {% else %}
                <div class="nav_dropdown" id="user_dropdown">
                  <button class="drop_button active">
                    <i class="fa-solid fa-user"></i>
                    Log In
                    <i class="fa fa-caret-down"></i>
                  </button>
                  <div class="nav_dropdown-content">
                    <a href="/accounts/login/?next={{ request.path }}">Log In</a>
                    <a href="/accounts/password_reset">Reset password</a>
                  </div>
                </div>
            {% endif %}
        <!--    <a href="#about">About</a>-->
            <a href="javascript:void(0);" class="menu_icon" id="menu_icon">&#9776;</a>
          </div>
        </div>
    </nav>

    {% if messages %}
        <div class="msg-container">
            <ul id="messages" class="msg-list">
                {% for message in messages %}
                    <li {% if message.tags %} class="single-msg {{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}

    {% block content %}{% endblock %}

</div>

<!--   Hidden field with username  -->
<textarea id="user-name" hidden>
    {{ user.first_name }} {{ user.last_name }}
</textarea>

<script type="text/javascript">
    // Save in this variable if there is an authenticated user
    // This variable is accessible on every other place in the code.
    {% if user.is_authenticated %}
        var user_authenticated = true;
    {% else %}
        var user_authenticated = false;
    {% endif %}
</script>

<footer class="site-footer">
    <div>
        <i>
            <!--       contact: jorisvos (at) uni-potsdam.de -->
            contact: aots (at) astro.physik.uni-potsdam.de
        </i>

        <i>
            source code: <a href="https://github.com/vosjo/AOTS">https://github.com/vosjo/AOTS</a>
        </i>

    </div>
</footer>

<!--    Cookie banner to comply with EU cookie law -->
<!--    https://github.com/dobarkod/cookie-banner/ -->
<script type="text/javascript" id="cookiebanner"
        src="https://cdn.jsdelivr.net/gh/dobarkod/cookie-banner@1.2.2/dist/cookiebanner.min.js"
        data-message="We use cookies to improve your browsing experience."
        moreinfo="https://en.wikipedia.org/wiki/HTTP_cookie">
</script>

</body>
</html>

templates/bokeh.html
{% load static %}
<!--<link href="{% static 'bokeh-0.12.1.min.css' %}" rel="stylesheet" type="text/css">
<script src="{% static 'bokeh-0.12.1.min.js' %}"></script> -->
<script src="https://cdn.pydata.org/bokeh/release/bokeh-3.8.1.min.js"></script>

templates/bokeh_widgets.html
<!--{% load static %}
<link href="{% static 'bokeh-widgets-0.12.1.min.css' %}" rel="stylesheet" type="text/css">
<script src="{% static 'bokeh-widgets-0.12.1.min.js' %}"></script> -->
<script src="https://cdn.pydata.org/bokeh/release/bokeh-widgets-3.8.1.min.js"></script>

templates/datatables.html
{% load static %}
<link href="{% static 'css/datatables.css' %}" rel="stylesheet" type="text/css">
<!-- <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>  -->
<!-- <script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script> -->
<!-- <script src="//cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script> -->
<script type="text/javascript" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
<!-- <script type="text/javascript" src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script> -->

templates/documentation.html
{% extends "landing.html" %}

{% load static %}

{% block head %}
    <!--
{   % include "datatables.html" %}
<script type="text/javascript" src="{% static 'js/tags_list.js' %}"></script>-->
    <title>Documentation</title>

{% endblock %}

{% block headertitle %} Documentation {% endblock %}

{% block content %}

    <section class='data-section' id="documentation_section">

        <h3 class='indent'>Docs</h3>


        <div class="flex-data-container j-center">


            <div class='docs-container'>

                <h3>
                    How to add a new spectrum
                </h3>

                <div>

                    <a href="/media/docs/Manual_add_spectrum.pdf">
                        <img class="project-logo" width="250px" src="{% static "images/docs_default_logo.png" %}">
                    </a>

                </div>

            </div>


            <div class='docs-container'>

                <h3>
                    How to add a new light curve
                </h3>

                <div>

                    <a href="/media/docs/Manual_add_lightcurve.pdf">
                        <img class="project-logo" width="250px" src="{% static "images/docs_default_logo.png" %}">

                </div>

            </div>

        </div>


    </section>

{% endblock %}

templates/landing.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="{% static 'css/base.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/fontawesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/fontawesome_regular.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/fontawesome_solid.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/jquery-ui.css' %}" rel="stylesheet" type="text/css">

    <script
            src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
            crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'js/base_js.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
    <link rel="icon" href="{% static 'favicon.ico' %}">
    {% block head %}{% endblock %}
</head>

<body>

<div class="page-wrap">
    <nav>
        <div class="nav_bar" id="mainNavBar">
          <a class="logo" href="/w/projects">
        <!--   <img src={% static "images/aotslogo.png" %}>-->
              AOTS
          </a>
<!--          <a class="title_line"><i class="site_title">{% block headertitle %}{% endblock %}</i></a>-->
          <div class="float_right">
            <a href="/" id="projects_a">
              <i class="fa-solid fa-diagram-project"></i>
              Projects
            </a>
            <a href="/w/documentation">
              <i class="fa-solid fa-book"></i>
              Guides
            </a>
            {% if user.is_authenticated %}
                <div class="nav_dropdown" id="user_dropdown">
                  <button class="drop_button active">
                    <i class="fa-solid fa-user"></i>
                    {{ user }}
                    <i class="fa fa-caret-down"></i>
                  </button>
                  <div class="nav_dropdown-content">
                    <a href="/users/you">View Profile</a>
                    <a href="/accounts/password_change">Change password</a>
                    <a href="/accounts/logout">Log Out</a>
                  </div>
                </div>
            {% else %}
                <div class="nav_dropdown" id="user_dropdown">
                  <button class="drop_button active">
                    <i class="fa-solid fa-user"></i>
                    Log In
                    <i class="fa fa-caret-down"></i>
                  </button>
                  <div class="nav_dropdown-content">
                    <a href="/accounts/login/?next={{ request.path }}">Log In</a>
                    <a href="/accounts/password_reset">Reset password</a>
                  </div>
                </div>
            {% endif %}
        <!--    <a href="#about">About</a>-->
            <a href="javascript:void(0);" class="menu_icon" id="menu_icon">&#9776;</a>
          </div>
        </div>
    </nav>

    <ul id="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>

    {% block content %}{% endblock %}
</div>

<script type="text/javascript">
    // Save in this variable if there is an authenticated user
    // This variable is accessible on every other place in the code.
    {% if user.is_authenticated %}
        var user_authenticated = true;
    {% else %}
        var user_authenticated = false;
    {% endif %}
</script>

<footer class="site-footer">
    <div>

        <i>
            <!--       contact: jorisvos (at) uni-potsdam.de -->
            contact: aots (at) astro.physik.uni-potsdam.de
        </i>

        <i>
            source code: <a href="https://github.com/vosjo/AOTS">https://github.com/vosjo/AOTS</a>
        </i>

    </div>
</footer>

<!--    Cookie banner to comply with EU cookie law -->
<!--    https://github.com/dobarkod/cookie-banner/ -->
<script type="text/javascript" id="cookiebanner"
        src="https://cdn.jsdelivr.net/gh/dobarkod/cookie-banner@1.2.2/dist/cookiebanner.min.js"
        data-message="We use cookies to improve your browsing experience."
        moreinfo="https://en.wikipedia.org/wiki/HTTP_cookie">
</script>

</body>
</html>