AOTS/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
# from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView, TemplateView
from rest_framework import routers

from stars import views as star_views
from stars.api.views import ProjectViewSet

router = routers.DefaultRouter()
router.register(r'projects', ProjectViewSet)

urlpatterns = [
                  path('', RedirectView.as_view(pattern_name='projects')),
                  path(
                      "robots.txt",
                      TemplateView.as_view(
                          template_name="robots.txt",
                          content_type="text/plain",
                      ),
                  ),

                  path(
                      'w/documentation/',
                      TemplateView.as_view(
                          template_name='documentation.html'
                      )
                  ),
                  path(
                      'w/projects/',
                      star_views.project_list,
                      name='projects',
                  ),
                  path(
                      'w/<slug:project>/',
                      RedirectView.as_view(pattern_name='dash:dashboard')
                  ),
                  path(
                      'w/<slug:project>/systems/',
                      include('stars.urls', namespace='systems')
                  ),
                  path(
                      'w/<slug:project>/observations/',
                      include(
                          'observations.urls',
                          namespace='observations'
                      )
                  ),
                  path(
                      'w/<slug:project>/dash/',
                      include('dash.urls', namespace='dash')
                  ),
                  path(
                      'w/<slug:project>/observations/',
                      RedirectView.as_view(
                          pattern_name='observations:observatory_list'
                      )
                  ),
                  path(
                      'w/<slug:project>/analysis/',
                      include('analysis.urls', namespace='analysis')
                  ),
                  path(
                      'w/<slug:project>/dashboard/',
                      RedirectView.as_view(pattern_name='dash:dashboard')
                  ),

                  path('api/', include(router.urls), name='project-api'),
                  path(
                      'api/systems/',
                      include("stars.api.urls", namespace='systems-api')
                  ),
                  path(
                      'api/observations/',
                      include(
                          "observations.api.urls",
                          namespace='observations-api'
                      )
                  ),
                  path(
                      'api/analysis/',
                      include(
                          "analysis.api.urls",
                          namespace='analysis-api'
                      )
                  ),
                  path(
                      'users/',
                      include(
                          "users.urls",
                          namespace='users'
                      )
                  ),

                  path(r'admin/', admin.site.urls),

                  # path('', RedirectView.as_view(url='/stars/stars/', permanent=False)),
                  # path('stars/', include('stars.urls', namespace='stars'), name='stars'),
                  # path('observations/', include('observations.urls'), name='observations'),
                  # path('analysis/', include('analysis.urls'), name='analysis'),

                  # path(r'api/stars/', include("stars.api.urls"), name='stars-api'),
                  # path(r'api/observations/', include("observations.api.urls"), name='observations-api'),
                  # path(r'api/analysis/', include("analysis.api.urls"), name='analysis-api'),

                  # path(r'^login/$', auth_views.login, name='login'),
                  # path(r'^logout/$', auth_views.logout, {'next_page': '/stars/stars'}, name='logout'),
                  # path(r'^change-password/$', auth_views.password_change, name='change-pwd'),
                  # path(r'^password-change-done/$', auth_views.password_change_done, name='password_change_done'),

                  # include all relevant user login/logout stuff. This includes:
                  #  accounts/login/ [name='login']
                  #  accounts/logout/ [name='logout']
                  #  accounts/password_change/ [name='password_change']
                  #  accounts/password_change/done/ [name='password_change_done']
                  #  accounts/password_reset/ [name='password_reset']
                  #  accounts/password_reset/done/ [name='password_reset_done']
                  #  accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
                  #  accounts/reset/done/ [name='password_reset_complete']
                  path('accounts/', include('django.contrib.auth.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dash/urls.py
from django.urls import path

from . import views

app_name = 'dash'
urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard')
]

stars/urls.py
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path
from django.views.generic.base import RedirectView

from . import views

app_name = 'systems'
urlpatterns = [
    path('stars/', views.star_list, name='star_list'),
    path('stars/<int:star_id>', views.star_detail, name='star_detail'),
    path('stars/<int:star_id>/edit', views.star_edit, name='star_edit'),
    path('tags/', views.tag_list, name='tag_list'),
    path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")),
    ),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('you/', views.thisUsersPage, name='personal_page'),
    path('user/<int:user_id>', views.foreignUsersPage, name='foreigners_page'),
]

dash/models.py
# Create your models here.

dash/forms.py
from django import forms


class HRDPlotterForm(forms.Form):
    from .labels import labeldict
    nsys = forms.ChoiceField(label="# Systems ",
                             required=True,
                             widget=forms.Select(),
                             choices=(
                                 (50, "50"),
                                 (100, "100"),
                                 (500, "500"),
                                 (1000, "1000"),
                                 (2500, "2500"),
                                 # ("all", "All")
                             ))

    xaxis = forms.ChoiceField(label="X-axis ",
                              required=True,
                              widget=forms.Select(),
                              choices=[
                                  (a, b) for a, b in labeldict.items()
                              ])

    yaxis = forms.ChoiceField(label="Y-axis ",
                              required=True,
                              widget=forms.Select(),
                              choices=[
                                  (a, b) for a, b in labeldict.items()
                              ])

    size = forms.ChoiceField(label="Size ",
                             required=False,
                             widget=forms.Select(),
                             choices=[
                                         (a, b) for a, b in labeldict.items()
                                     ] + [(None, "None")])

    color = forms.ChoiceField(label="Color ",
                              required=False,
                              widget=forms.Select(),
                              choices=[
                                          (a, b) for a, b in labeldict.items()
                                      ] + [(None, "None")])

    def get_parameters(self):
        return {'xaxis': self.cleaned_data['xaxis'],
                'yaxis': self.cleaned_data['yaxis'],
                'size': self.cleaned_data['size'],
                'color': self.cleaned_data['color'],
                'nsys': self.cleaned_data["nsys"]}

dash/views.py
import logging
import time
from datetime import datetime, timedelta
from itertools import chain

from bokeh.embed import components
from bokeh.resources import CDN
from django.shortcuts import get_object_or_404, render
from django.utils.timezone import make_aware

from AOTS.custom_permissions import check_user_can_view_project
from analysis.models import DataSet
from observations.models import Spectrum, LightCurve
from stars.models import Project, Star
from .forms import HRDPlotterForm
from .plotting import plot_hrd


def sort_modified_created(model):
    try:
        return model.history.latest().history_date
    except AttributeError:
        return datetime.fromisoformat("1970-01-01")


def get_modeltype(instance):
    for model, modelname in zip([Star, Spectrum, LightCurve, DataSet], ["Star", "Spectrum", "LightCurve", "DataSet"]):
        if isinstance(instance, model):
            return modelname


def wascreated(mod):
    # Modifications within the first 5 minutes of an object being created should not make the object count as having been modified
    earliest_history = mod.history.earliest()
    latest_history = mod.history.latest()

    time_diff = latest_history.history_date - earliest_history.history_date

    if time_diff <= timedelta(minutes=5):
        return True
    else:
        return False


@check_user_can_view_project
def dashboard(request, project=None, **kwargs):
    parameters = {}

    if request.method == 'GET':
        form = HRDPlotterForm(request.GET)
        if form.is_valid():
            parameters = form.get_parameters()
        else:
            form = HRDPlotterForm(initial={
                'nsys': 50,
                'xaxis': 'bp_rp',
                'yaxis': "mag_abs",
                "size": "",
                "color": "",
                })
    else:
        form = HRDPlotterForm(initial={
            'nsys': 50,
            'xaxis': 'bp_rp',
            'yaxis': "mag_abs",
            "size": "",
            "color": "",
            })

    stats = {}
    project = get_object_or_404(Project, slug=project)

    dtime_naive = datetime.now() - timedelta(days=7)
    aware_datetime = make_aware(dtime_naive)

    start = time.time()

    all_models = []

    # A warning for those who come after me: Do not try to optimize this further, it can only bring you despair.
    for mod, modname in zip([Star, Spectrum, LightCurve, DataSet], ["nstars", "nspec", "nlc", "naly"]):
        all_mod_objs = mod.objects.filter(project=project)
        all_mod_hists = mod.history.filter(project=project)

        most_recent = all_mod_hists.order_by("-history_date")[:25]
        most_recent_ids = most_recent.values_list('id', flat=True)
        most_recent_models = all_mod_objs.filter(pk__in=most_recent_ids)

        all_models.append(most_recent_models)

        stats[modname] = all_mod_objs.count()

        # First history entry must be more recent than seven days ago
        all_mod_objs_lw = all_mod_hists.filter(history_date__gte=aware_datetime)
        stats[modname + "lw"] = all_mod_objs_lw.count()

    recent_changes = sorted(chain(*all_models), key=sort_modified_created, reverse=True)[:25]

    recent_changes = [{"modeltype": get_modeltype(r), "date": r.history.latest().history_date, "user": r.history.latest().history_user if r.history.latest().history_user is not None else "unknown", "instance": r, "created": wascreated(r)} for r in
                      recent_changes]
    # Possible axes teff, logg, mag, bp_rp
    if len(parameters.keys()) != 0:
        figure = plot_hrd(request, project.pk, parameters["xaxis"], parameters["yaxis"], parameters["size"], parameters["color"], parameters["nsys"])
        script, div = components(figure, CDN)
    else:
        figure = plot_hrd(request, project.pk)
        script, div = components(figure, CDN)

    context = {
        'project': project,
        'stats': stats,
        'recent_changes': recent_changes,
        'hrd_plot': div,
        'script': script,
        'form': enumerate(form)
    }

    end = time.time()
    logger = logging.getLogger("django")
    logger.error(f"Time elapsed to generate dash: {end-start}s")

    return render(request, 'dash/dashboard.html', context)

dash/templates/dash/dashboard.html
{% extends "base.html" %}
{% load static %}

{% block head %}
    {% include "bokeh.html" %}
    <script type="text/javascript" src="{% static 'js/dashboard.js' %}"></script>
    <title>Project dashboard</title>

{% endblock %}

{% block headertitle %} Dashboard {% endblock %}

{% block content %}
    <div class="dashboard-wrapper">
        <div class="dash-upperrow">
            {#            <div class="dash-square dash-upper-left "><h1>Project Statistics</h1>#}
            {#                <br>#}
            {#                <p class="stats">Number of Stars: <b>{{ stats.nstars }}</b>{% if stats.nstarslw != 0 %}#}
            {#                    <span style="color: #228B22"> + <b>{{ stats.nstarslw }}</b> last week</span>{% endif %}</p>#}
            {#                <p class="stats">Of which with Spectra: <b>{{ stats.nspec }}</b> {% if stats.nspeclw != 0 %}#}
            {#                    <span style="color: #228B22"> +<b>{{ stats.nspeclw }}</b> spectra last week</span>{% endif %}</p>#}
            {#                <p class="stats">Number of Lightcurves: <b>{{ stats.nlc }}</b>{% if stats.nlclw != 0 %}#}
            {#                    <span style="color: #228B22"> + <b>{{ stats.nlclw }}</b> last week</span>{% endif %}</p>#}
            {#            </div>#}
            <div class="dash-square dash-upper-left dash-systems">
                <a onclick="location.href='../../systems/stars'">
                    <span class="divlink">
                    </span>
                </a>
                <span class="dash-stats-title">Systems</span>
                <b class="counter">{{ stats.nstars }}</b>
                {% if stats.nstarslw != 0 %}
                    <span style="color: #228B22"> + <b>{{ stats.nstarslw }}</b> last week</span>
                {% endif %}
            </div>
            <div class="dash-square dash-upper-left dash-spec">
                <a onclick="location.href='../../observations/spectra'">
                    <span class="divlink">
                    </span>
                </a>
                <span class="dash-stats-title">Spectra</span>
                <b class="counter">{{ stats.nspec }}</b>
                {% if stats.nspeclw != 0 %}
                    <span style="color: #228B22"> + <b>{{ stats.nspeclw }}</b> last week</span>
                {% endif %}
            </div>
            <div class="dash-square dash-upper-left dash-lc">
                <a onclick="location.href='../../observations/lightcurves'">
                    <span class="divlink">
                    </span>
                </a>
                <span class="dash-stats-title">Lightcurves</span>
                <b class="counter">{{ stats.nlc }} </b>
                {% if stats.nlclw != 0 %}
                    <span style="color: #228B22"> + <b>{{ stats.nlclw }}</b> last week</span>
                {% endif %}
            </div>
            <div class="dash-square dash-upper-left dash-aly">
                <a onclick="location.href='../../analysis/datasets'">
                    <span class="divlink">
                    </span>
                </a>
                <span class="dash-stats-title">Datasets</span>
                <b class="counter">{{ stats.naly }}</b>
                {% if stats.nlclw != 0 %}
                    <span style="color: #228B22"> + <b>{{ stats.nalylw }}</b> last week</span>
                {% endif %}
            </div>
            <div class="dash-project-sky-preview-wrapper">
                {% if project.preview_starmap %}
                    <img class="project-logo" src="{{ project.preview_starmap.url }}" alt="{{ project.name }} Starmap" onclick="openDetailedStarmap()">
                {% else %}
                    <img class="project-logo" src="{% static "images/default_logo.png" %}" alt="{{ project.name }} Starmap">
                {% endif %}
            </div>
            <div class="dash-upper-right">
                <button class="dash-button top-button left-button" onclick="location.href='../../systems/stars'" type="button">
                    <i class="icon material-icons dash-icon">auto_awesome</i> Systems
                </button>
                <button class="dash-button top-button right-button" onclick="location.href='../../observations/spectra'" type="button">
                    <i class="icon material-icons dash-icon">insights</i> Spectra
                </button>
                <button class="dash-button bottom-button left-button" onclick="location.href='../../observations/lightcurves'" type="button">
                    <i class="icon material-icons dash-icon">flare</i> Lightcurves
                </button>
                <button class="dash-button bottom-button right-button" onclick="location.href='../../analysis/datasets'" type="button">
                    <i class="icon material-icons dash-icon">bar_chart</i> Analysis
                </button>
            </div>
        </div>
        <div class="dash-lowerrow">
            <div class="dash-square dash-lower-left">
<!--                 <h2>Project Overview</h2> -->
                <h2>Object parameters</h2>
                <div class="dash-overview-plot">
                    {{ hrd_plot|safe }}
                </div>
                <div class="dash-overview-params">
                    <form action="{% url "dash:dashboard" project.slug %}" method="get">
                        {% csrf_token %}
                        <table>
                            <tbody>
                            {% for ind, field in form %}
                                <tr id="tr_{{ ind }}">
                                    <th>{{ field.label_tag }}</th>
                                    <td>
                                        {{ field }}
                                    <td>
                                    <td style="color:red;">
                                        {{ field.errors }}
                                    <td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                        <input id="submitbtn" type="submit" value="Update Figure"/>
                    </form>
                </div>
            </div>
            <div class="dash-square dash-lower-center"><h2>Observation requests</h2>
                <p style="font-size: large">This section is <b>Under Construction!</b></p>
            </div>
            <div class="dash-square dash-lower-right"><h2 class="latest-changes">Latest changes</h2>
                <div class="dash-changelog-container">
                    {% for event in recent_changes %}
                        <div class="dash-changelog-field">
                            {% if event.modeltype == "Star" %}
                                <b class="dash-changelog-field-title">
                                    <a href={% url 'systems:star_detail' project.slug event.instance.pk %}>{{ event.instance.name }}</a> was
                                    {% if event.created %} created{% else %} modified{% endif %}</b><br>
                                by<b class="dash-changelog-field-name">
                                {% if event.user == 'unknown' %}unknown{% else %}<a href={% url 'users:foreigners_page' event.user.pk %}>{{ event.user.username }}</a>{% endif %}</b>, {{ event.date }}
                            {% elif event.modeltype == "Spectrum" and event.instance.star is not None %}
                                <b class="dash-changelog-field-title"> A spectrum for
                                    <a href={% url 'systems:star_detail' project.slug event.instance.star.pk %}>{{ event.instance.star.name }}</a> was
                                    {% if event.created %} created{% else %} modified {% endif %}</b><br>
                                by<b class="dash-changelog-field-name">
                                {% if event.user == 'unknown' %}unknown{% else %}<a href={% url 'users:foreigners_page' event.user.pk %}>{{ event.user.username }}</a>{% endif %}</b>, {{ event.date }}
                            {% elif event.modeltype == "LightCurve" and event.instance.star is not None %}
                                <b class="dash-changelog-field-title"> A lightcurve for
                                    <a href={% url 'systems:star_detail' project.slug event.instance.star.pk %}>{{ event.instance.star.name }}</a> was
                                    {% if event.created %} created{% else %} modified {% endif %}</b><br>
                                by<b class="dash-changelog-field-name">
                                {% if event.user == 'unknown' %}unknown{% else %}<a href={% url 'users:foreigners_page' event.user.pk %}>{{ event.user.username }}</a>{% endif %}</b>, {{ event.date }}
                            {% elif event.modeltype == "DataSet" and event.instance.star is not None %}
                                <b class="dash-changelog-field-title"> A dataset for
                                    <a href={% url 'systems:star_detail' project.slug event.instance.star.pk %}>{{ event.instance.star.name }}</a> was
                                    {% if event.created %} created{% else %} modified {% endif %}</b><br>
                                by<b class="dash-changelog-field-name">
                                {% if event.user == 'unknown' %}unknown{% else %}<a href={% url 'users:foreigners_page' event.user.pk %}>{{ event.user.username }}</a>{% endif %}</b>, {{ event.date }}
                            {% endif %}
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <div id="detailedStarmap" title="Copy Photometry">
        {% if project.full_starmap %}
            <img class="full-starmap" src="{{ project.full_starmap.url }}" alt="{{ project.name }} logo">
        {% endif %}
    </div>
    {{ script|safe }}
{% endblock %}